# Generated by Django 5.1.3 on 2024-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="file",
            field=models.ImageField(blank=True, default="", upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tel",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="working_hours",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
