# Generated by Django 5.1.3 on 2024-12-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_auth_app",
            "0002_alter_userprofile_description_alter_userprofile_file_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
