# Generated by Django 5.1.3 on 2025-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerdetail",
            name="features",
            field=models.CharField(max_length=255),
        ),
    ]
