# Generated by Django 5.1.3 on 2025-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_alter_offerdetail_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerdetail",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
