# Generated by Django 5.1.3 on 2025-02-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_alter_offerdetail_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerdetail",
            name="features",
            field=models.JSONField(),
        ),
    ]
