# Generated by Django 5.1.3 on 2025-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_alter_offerdetail_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerdetail",
            name="title",
            field=models.CharField(default="Default Title", max_length=50),
            preserve_default=False,
        ),
    ]
